# Generated by Django 3.2.4 on 2021-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flag', models.BinaryField()),
                ('symbol', models.CharField(max_length=10)),
                ('abv', models.CharField(max_length=10)),
                ('avtive', models.BooleanField()),
            ],
        ),
    ]
