# Generated by Django 3.2.4 on 2021-06-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_avtive_currency_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='flag',
        ),
        migrations.AddField(
            model_name='currency',
            name='country_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
