# Generated by Django 3.2.4 on 2021-06-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210620_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='flag_linek',
            field=models.CharField(default='', max_length=100),
        ),
    ]
