# Generated by Django 3.2.4 on 2021-06-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_currency_flag_linek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='flag_linek',
            new_name='flag_link',
        ),
    ]
