# Generated by Django 3.2.4 on 2021-06-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_flag_linek_currency_flag_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.FloatField(default=1),
        ),
    ]
